### ISSUE TITLE
[BUG] after installing studio fails to launch

### ISSUE THREAD

**Issue by iiasceri** [JesusFreke/smalidea#26]
Internal error. Please refer to https://code.google.com/p/android/issues

com.intellij.ide.plugins.PluginManagerCore$EssentialPluginMissingException: Missing essential plugins: com.android.tools.design, org.jetbrains.android
    at com.intellij.ide.plugins.PluginManagerCore.checkEssentialPluginsAreAvailable(PluginManagerCore.java:761)
    at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:854)
    at com.intellij.ide.plugins.PluginManagerCore.initializeAndSetPlugins(PluginManagerCore.java:1068)
    at com.intellij.ide.plugins.PluginDescriptorLoader$scheduleLoading$pluginSetDeferred$1.invokeSuspend(PluginDescriptorLoader.kt:397)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

-----
Your JRE: 17.0.7+0-17.0.7b829.16-10353782 aarch64 (JetBrains s.r.o.)
/Applications/Android Studio Preview.app/Contents/jbr/Contents/Home

**Comment by Bymistytea** [comment]
Hello, I noticed your mistake. It's the same as mine. Did you find how to fix it?

**Comment by iiasceri** [comment]
Fix studio you clean caches etc (reinstall)
Fix plugin loading that is causing this you disable smali from google
Fix code then just ping creator or do a fork with chat gpt ask how to do stuff
